### ISSUE TITLE
tensorflow import error

### ISSUE THREAD

**Issue by patricxu** [alibaba/graph-learn#12]
CentOS 7
python 2.7.5
tensorflow 1.12.0

I have built GL from source successfully and passed ./test_cpp_ut.sh. But when I try ./test_python_ut.sh, I got stuck by the import errors.

`ImportError: cannot import name abs
./graphlearn/python/tests/test_node_weighted.py
Traceback (most recent call last):
  File "./graphlearn/python/tests/test_node_weighted.py", line 23, in <module>
    import graphlearn as gl
  File "/usr/lib64/python2.7/site-packages/graphlearn/__init__.py", line 33, in <module>
    from graphlearn.python.model.tf import aggregators
  File "/usr/lib64/python2.7/site-packages/graphlearn/python/model/tf/aggregators/__init__.py", line 20, in <module>
    from graphlearn.python.model.tf.aggregators.gcn_aggregator import GCNAggregator
  File "/usr/lib64/python2.7/site-packages/graphlearn/python/model/tf/aggregators/gcn_aggregator.py", line 20, in <module>
    import tensorflow as tf
  File "/usr/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 88, in <module>
    from tensorflow.python import keras
  File "/usr/lib/python2.7/site-packages/tensorflow/python/keras/__init__.py", line 24, in <module>
    from tensorflow.python.keras import activations
  File "/usr/lib/python2.7/site-packages/tensorflow/python/keras/activations/__init__.py", line 22, in <module>
    from tensorflow.python.keras._impl.keras.activations import elu
  File "/usr/lib/python2.7/site-packages/tensorflow/python/keras/_impl/keras/__init__.py", line 21, in <module>
    from tensorflow.python.keras._impl.keras import activations
  File "/usr/lib/python2.7/site-packages/tensorflow/python/keras/_impl/keras/activations.py", line 23, in <module>
    from tensorflow.python.keras._impl.keras import backend as K
  File "/usr/lib/python2.7/site-packages/tensorflow/python/keras/_impl/keras/backend.py", line 38, in <module>
    from tensorflow.python.layers import base as tf_base_layers
  File "/usr/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 25, in <module>
    from tensorflow.python.keras.engine import base_layer
  File "/usr/lib/python2.7/site-packages/tensorflow/python/keras/engine/__init__.py", line 23, in <module>
    from tensorflow.python.keras.engine.base_layer import InputSpec
  File "/usr/lib/python2.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 35, in <module>
    from tensorflow.python.keras import backend
  File "/usr/lib/python2.7/site-packages/tensorflow/python/keras/backend/__init__.py", line 22, in <module>
    from tensorflow.python.keras._impl.keras.backend import abs
`

I believe the error comes from inconsistency of TF and it's dependencies according to the [THREADS](https://github.com/tensorflow/probability/issues/46). I have tried many combinations among the packages but still failed. 

Could you provide the DETAILED VERSION of TF's dependencies?

**Comment by baoleai** [comment]
Have you tried uninstalling TF&protobuf and deleting TF dir in site-packages and reinstalling TF? 
I suggest you try it out using a virtual environment like conda.

**Comment by patricxu** [comment]
I degraded TF to 1.8.0 then passed ./test_python_ut.sh

`----------------------------------------------------------------------
Ran 1 test in 0.017s

OK
[2020-04-03 22:32:44.572600] Server stopped.
./graphlearn/python/tests/test_node_weighted_labeled.py
/usr/lib64/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
[2020-04-03 22:32:45.225500] Server started.
[2020-04-03 22:32:45.229333] Data initialized.
.
----------------------------------------------------------------------
Ran 1 test in 0.017s

OK
[2020-04-03 22:32:45.230029] Server stopped.
./graphlearn/python/tests/test_node_weighted.py
/usr/lib64/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
[2020-04-03 22:32:45.885681] Server started.
[2020-04-03 22:32:45.888963] Data initialized.
.
----------------------------------------------------------------------
Ran 1 test in 0.016s

OK
[2020-04-03 22:32:45.889528] Server stopped.
`

I will try the virtual env

**Comment by patricxu** [comment]
I degrade TF to 1.8.0 and passed. I will try the virtual env.

**Comment by patricxu** [comment]
@baoleai I made it in virtual env. Thanks!!
