### ISSUE TITLE
k8s跑graphsage集群模式下ResourceExhaustedError问题

### ISSUE THREAD

**Issue by zhxchnl** [alibaba/graph-learn#161]
你好，
我使用graph-learn在一份较大的图数据上测试graphsage的结果。图有6千万的节点，8千万的边，初始化的node feature使用128维的向量，最终输出也是128维向量。任务在kubernetes上运行。
目前遇到两个问题：
1，在batch size 设置>5的情况下，worker节点刚开始跑就会报ResourceExhaustedError。但此时不论是worker节点还是ps节点内存使用和cpu使用率都不太高<50%。尝试设置gl.set_rpc_message_max_size(50000000)没有作用。具体错误信息如下：

2021-08-24 11:38:36.938359: W tensorflow/core/framework/op_kernel.cc:1389] Unknown: ResourceExhaustedError: 8
Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/script_ops.py", line 207, in __call__
    ret = func(*args)

  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 449, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/usr/local/lib/python2.7/dist-packages/graphlearn/python/model/tf/ego_flow.py", line 229, in _sample_generator
    neg_dst_recept.flatten(spec = self._dst_ego_spec)

  File "/usr/local/lib/python2.7/dist-packages/graphlearn/python/model/ego_graph.py", line 68, in flatten
    spec.hops_spec[i].sparse))

  File "/usr/local/lib/python2.7/dist-packages/graphlearn/python/model/ego_graph.py", line 108, in _flatten_impl
    int_attrs = feature.int_attrs # [num_int_attrs, ids.shape]

  File "/usr/local/lib/python2.7/dist-packages/graphlearn/python/values.py", line 58, in int_attrs
    self._set_attrs()

  File "/usr/local/lib/python2.7/dist-packages/graphlearn/python/values.py", line 155, in _set_attrs
    self._lookup_and_set_values()

  File "/usr/local/lib/python2.7/dist-packages/graphlearn/python/values.py", line 278, in _lookup_and_set_values
    values = self._graph.lookup_nodes(self._type, self._ids)

  File "/usr/local/lib/python2.7/dist-packages/graphlearn/python/graph.py", line 603, in lookup_nodes
    raise_exception_on_not_ok_status(self._client.lookup_nodes(req, res))

  File "/usr/local/lib/python2.7/dist-packages/graphlearn/python/errors.py", line 220, in raise_exception_on_not_ok_status
    raise _make_specific_exception(status.message(), int(status.code()))

ResourceExhaustedError: 8

graph_cluster: {'client_count': 5, 'tracker': '../../distributed/', 'server_count': 15}
main
neighs_num 2, conv layer 2, depth 2
training...
Traceback (most recent call last):
  File "dist_train_unsupervised.py", line 141, in <module>
    main()
  File "dist_train_unsupervised.py", line 136, in main
    train(config, g)
  File "dist_train_unsupervised.py", line 99, in train
    trainer.train()
  File "/usr/local/lib/python2.7/dist-packages/graphlearn/python/model/tf/trainer.py", line 237, in train
    self._train_epoch(train_op, loss, train_iterator, i)
  File "/usr/local/lib/python2.7/dist-packages/graphlearn/python/model/tf/trainer.py", line 87, in _train_epoch
    feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 676, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1171, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1270, in run
    raise six.reraise(*original_exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1255, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1327, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1091, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: ResourceExhaustedError: 8
Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/script_ops.py", line 207, in __call__
    ret = func(*args)

  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 449, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/usr/local/lib/python2.7/dist-packages/graphlearn/python/model/tf/ego_flow.py", line 229, in _sample_generator
    neg_dst_recept.flatten(spec = self._dst_ego_spec)

  File "/usr/local/lib/python2.7/dist-packages/graphlearn/python/model/ego_graph.py", line 68, in flatten
    spec.hops_spec[i].sparse))

  File "/usr/local/lib/python2.7/dist-packages/graphlearn/python/model/ego_graph.py", line 108, in _flatten_impl
    int_attrs = feature.int_attrs # [num_int_attrs, ids.shape]

  File "/usr/local/lib/python2.7/dist-packages/graphlearn/python/values.py", line 58, in int_attrs
    self._set_attrs()

  File "/usr/local/lib/python2.7/dist-packages/graphlearn/python/values.py", line 155, in _set_attrs
    self._lookup_and_set_values()

  File "/usr/local/lib/python2.7/dist-packages/graphlearn/python/values.py", line 278, in _lookup_and_set_values
    values = self._graph.lookup_nodes(self._type, self._ids)

  File "/usr/local/lib/python2.7/dist-packages/graphlearn/python/graph.py", line 603, in lookup_nodes
    raise_exception_on_not_ok_status(self._client.lookup_nodes(req, res))

  File "/usr/local/lib/python2.7/dist-packages/graphlearn/python/errors.py", line 220, in raise_exception_on_not_ok_status
    raise _make_specific_exception(status.message(), int(status.code()))

ResourceExhaustedError: 8

[[{{node PyFunc}}]]
[[node IteratorGetNext (defined at /usr/local/lib/python2.7/dist-packages/graphlearn/python/model/tf/ego_flow.py:302) ]]
I0824 11:38:37.322377    18 naming_engine.cc:159] Refresh endpoints count: 15

2，看文档ps节点的数量应该就是图被分片的数量，但设置8个ps节点和15个ps节点的时候节点的占用内存几乎一样，15个ps节点的每个节点占用内存没有比8个更小。这个让人有点迷惑。

期待你的解答

**Comment by Seventeen17** [comment]
集群模式下，每个ps都会加载全部的数据，因此需要对数据源进行提前分片，让每个ps只加载一个partition
