### ISSUE TITLE
Installation on Ubuntu 18.04

### ISSUE THREAD

**Issue by kanonjz** [alibaba/graph-learn#8]
I try to install graph-learn from source. when I run `make python`, I get the following error:
My python version is 3.74.
```
python /home/kanon/code/graph-learn/setup/setup.py bdist_wheel
/home/kanon/anaconda3/lib/python3.7/site-packages/setuptools/dist.py:462: UserWarning: The version specified (b'0.1') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version
running bdist_wheel
Traceback (most recent call last):
  File "/home/kanon/code/graph-learn/setup/setup.py", line 85, in <module>
    package_data={'': ['python/lib/lib*.so*']},
  File "/home/kanon/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/home/kanon/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/kanon/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/kanon/anaconda3/lib/python3.7/distutils/dist.py", line 984, in run_command
    cmd_obj.ensure_finalized()
  File "/home/kanon/anaconda3/lib/python3.7/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/home/kanon/anaconda3/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 129, in finalize_options
    self.data_dir = self.wheel_dist_name + '.data'
  File "/home/kanon/anaconda3/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 164, in wheel_dist_name
    safer_version(self.distribution.get_version()))
  File "/home/kanon/anaconda3/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 43, in safer_version
    return safe_version(version).replace('-', '_')
  File "/home/kanon/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1333, in safe_version
    return str(packaging.version.Version(version))
  File "/home/kanon/anaconda3/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 200, in __init__
    match = self._regex.search(version)
TypeError: cannot use a string pattern on a bytes-like object
Makefile:317: recipe for target 'python' failed
make: *** [python] Error 1
```

**Comment by Seventeen17** [comment]
Please use Python2 for now, we will support Python3 soon.

**Comment by kanonjz** [comment]
OK. Thanks.
